repos:
  # === Linting and Formatting (Auto-fix Mode)===
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.4
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix]
      # Run the formatter
      - id: ruff-format

  # === General Pre-commit Hooks for Good Practice ===
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # Use a recent, specific version
    hooks:
      - id: trailing-whitespace     # Checks for trailing whitespace (fixes by default)
      - id: end-of-file-fixer       # Ensures files end with one newline (fixes by default)
      - id: check-yaml              # Checks YAML syntax
      - id: check-toml              # Checks TOML syntax (good for pyproject.toml)
      - id: check-added-large-files # Prevents committing large files
      - id: check-merge-conflict    # Checks for leftover merge conflict markers
